"use server";

import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";

import { canManageInvitations, isMemberRole } from "@/lib/auth/roles";
import { requireRole } from "@/lib/auth/session";
import { createClient } from "@/lib/supabase/server";

const EXPIRY_DAYS = new Set(["7", "30", "90"]);

function back(error?: string): never {
  revalidatePath("/admin/invitations");
  redirect(
    error
      ? `/admin/invitations?error=${encodeURIComponent(error)}`
      : "/admin/invitations",
  );
}

export async function createInvitation(formData: FormData) {
  const viewer = await requireRole(canManageInvitations, "/admin/invitations");
  const supabase = await createClient();

  const role = String(formData.get("role") ?? "member");
  const expiry = String(formData.get("expires_in") ?? "30");
  const email = String(formData.get("email") ?? "").trim();

  if (!isMemberRole(role)) back("Unknown role.");

  // "Never" is deliberately offered: an open-link org pins one invitation to a
  // newsletter and leaves it there.
  const expiresAt = EXPIRY_DAYS.has(expiry)
    ? new Date(Date.now() + Number(expiry) * 86_400_000).toISOString()
    : null;

  // The token itself is generated by the column default — 18 random bytes, hex
  // encoded (0001_init.sql) — so it is never chosen by application code.
  const { error } = await supabase.from("invitations").insert({
    org_id: viewer.membership.org_id,
    role,
    email: email || null,
    expires_at: expiresAt,
    created_by: viewer.userId,
  });

  back(error ? "Could not create that invitation." : undefined);
}

export async function revokeInvitation(formData: FormData) {
  const viewer = await requireRole(canManageInvitations, "/admin/invitations");
  const supabase = await createClient();

  const id = String(formData.get("invitation_id") ?? "");

  // Revoked rather than deleted: an admin should still be able to see that a
  // link existed and who created it.
  const { error } = await supabase
    .from("invitations")
    .update({ revoked_at: new Date().toISOString() })
    .eq("id", id)
    .eq("org_id", viewer.membership.org_id);

  back(error ? "Could not revoke that invitation." : undefined);
}
